name: guillem_curriculum
description: Guillem's curriculum vitae.
publish_to: "none"
version: 0.5.1+9

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  any_link_preview: ^3.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.17+3
  flutter_web_plugins:
    sdk: flutter
  collection: ^1.17.0
  desktop_window: ^0.4.0
  drop_cap_text: ^1.1.3
  equatable: ^2.0.5
  extra_alignments: ^1.0.0+1
  flextras: ^1.0.0
  firebase_crashlytics: ^3.3.5
  firebase_core: ^2.15.1
  flutter_animate: ^1.0.0
  flutter_circular_text: ^0.3.1
  flutter_displaymode: ^0.5.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.1
  gap:
    git:
      url: https://github.com/esDotDev/gap.git
      ref: dc980bf
  get_it: ^7.2.0
  get_it_mixin: ^3.1.4
  go_router: ^10.1.2
  http: ^1.1.0
  image_fade: ^0.6.2
  image_gallery_saver: ^2.0.3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  package_info_plus: ^4.1.0
  particle_field: ^0.0.1
  path_provider: ^2.0.12
  provider: ^6.0.5
  rnd: ^0.2.0
  shared_preferences: ^2.2.0
  simple_rich_text: ^2.0.49
  sized_context: ^1.0.0+1
  smooth_page_indicator: ^1.0.1
  unsplash_client: ^2.1.1
  webview_flutter: ^4.2.2
  youtube_player_iframe: ^4.0.4
  url_launcher: ^6.1.14

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_gen_runner: ^5.3.1
  copy_with_extension_gen: ^4.0.3
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.1
  # dart_code_metrics: ^4.17.1
  dependency_validator: ^3.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/_common/
    - assets/images/_common/icons/
    - assets/images/_common/texture/
    - assets/images/software/
    - assets/images/crypto/
    - assets/images/marketing/
    - assets/images/chatbot/
    - assets/images/others/

  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
        - asset: assets/fonts/CinzelDecorative-Black.ttf
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
    - family: Yeseva
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
    - family: Tenor
      fonts:
        - asset: assets/fonts/TenorSans-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: MaShanZheng
      fonts:
        - asset: assets/fonts/MaShanZheng-Regular.ttf
    - family: B612Mono
      fonts:
        - asset: assets/fonts/B612Mono-Regular.ttf
