// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk23CP_5GkpD8MA3VskJIe0DETjWaZY_A',
    appId: '1:123445088604:web:984ce3965918fa2357b199',
    messagingSenderId: '123445088604',
    projectId: 'app-curriculum-iag7lg',
    authDomain: 'app-curriculum-iag7lg.firebaseapp.com',
    storageBucket: 'app-curriculum-iag7lg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_-MlyZQ2v3nMcQzE_N02q9X8onAP-v5o',
    appId: '1:123445088604:android:c36233045b641a8e57b199',
    messagingSenderId: '123445088604',
    projectId: 'app-curriculum-iag7lg',
    storageBucket: 'app-curriculum-iag7lg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsntaemkRIckfwTkYKy8or3ZUukZm1HgU',
    appId: '1:123445088604:ios:73b7e51379f74a1357b199',
    messagingSenderId: '123445088604',
    projectId: 'app-curriculum-iag7lg',
    storageBucket: 'app-curriculum-iag7lg.appspot.com',
    iosClientId: '123445088604-oihcq7nu4tf4r9qshhf4l2t204son6ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.guillemCurriculum',
  );
}
